on:
  pull_request:
    branches:
      - main
    paths:
      - "src/nata.sh"
      - "examples/config.json"
      - "test/test.bats"
  push:
    branches:
      - main
    paths:
      - "src/nata.sh"
      - "examples/config.json"
      - "test/test.bats"

jobs:
  my_test:
    runs-on: ubuntu-latest
    name: Install Bats and Run Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bats and Bats Libraries
        id: setup-bats
        uses: bats-core/bats-action@3.0.0
        with:
          support-path: "${{ github.workspace }}/tests/bats-support"
          assert-path: "${{ github.workspace }}/tests/bats-assert"
          detik-path: "${{ github.workspace }}/tests/bats-detik"
          file-path: "${{ github.workspace }}/tests/bats-file"

      - name: Run Bats Tests
        shell: bash
        env:
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
          TERM: xterm
        run: bats test/test.bats
